# Site settings
title: Front-End Development and Design
email: basitmate@live.com
description: > # this means to ignore newlines until "baseurl:"
  Wow. Much quick. Very inexpensive. Much Design. wow.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.dblogg.com/" # the base hostname & protocol for your site
twitter_username: basitmate
github_username:  basitmate

# Build settings
markdown: kramdown
