# Site settings
title: Test Site #1
email: basitmate@live.com
description: > # this means to ignore newlines until "baseurl:"
  Wow. Much speed, very simple.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dblogg.com" # the base hostname & protocol for your site
twitter_username: basitmate
github_username:  basitmate

# Build settings
markdown: kramdown
