# Site settings
title: Front-End Designer - Email and Web Development
email: basitmate@live.com
description: > # this means to ignore newlines until "baseurl:"
  This is a blog about Email Development and Web Development ran by Sheikh Basit
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://frontenddesigner.com" # the base hostname & protocol for your site
twitter_username: basitmate
github_username:  basitmate

# Build settings
highlighter: rough
markdown: kramdown
